hw-online-book-store
savchenkoarts/online-book-store pull request #1
Opened 2024-01-14 14:28 UTC by savchenkoarts

2024-01-14 17:23 UTC, Rommelua requested changes

2024-01-14 17:23 UTC, Rommelua commented on src/main/java/mate/academy/onlinebookstore/repository/BookRepositoryImpl.java
> +        return null;
implement methods

2024-01-14 17:23 UTC, Rommelua commented on src/main/java/mate/academy/onlinebookstore/service/BookServiceImpl.java
> +        return null;
implement methods

2024-01-14 17:23 UTC, Rommelua commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +public class Book {
constraints?
![image](https://github.com/savchenkoarts/online-book-store/assets/20326858/1b11c49d-09c6-4b15-a3eb-ef9a00b57ae8)

2024-01-20 18:46 UTC, sokimaaa commented on src/main/java/mate/academy/onlinebookstore/OnlineBookStoreApplication.java
> +    private BookService bookService;
Wrong way to inject bean.
Inject directly via method params in the @Bean method.

```suggestion
```

2024-01-20 18:47 UTC, sokimaaa commented on src/main/java/mate/academy/onlinebookstore/OnlineBookStoreApplication.java
> +        };
use lambda (not anonymous class)
```suggestion
        return new CommandLineRunner() {
            @Override
            public void run(String... args) throws Exception {
                Book book = new Book();
                book.setCoverImage("image");
                book.setIsbn("Ranok");
                book.setDescription("About nature");
                book.setTitle("From nature");
                book.setPrice(BigDecimal.valueOf(500));
                book.setAuthor("Stiven");

                bookService.save(book);

                System.out.println(bookService.findAll());
            }
        };
```

2024-01-20 18:48 UTC, sokimaaa commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +    @Column(nullable = false)
notNull, notBlank are not `constraints`. Remove annotations that you don't know how to use. 
```suggestion
    @Column(nullable = false)
    private String title;
    @Column(nullable = false)
    private String author;
    @Column(nullable = false, unique = true)
    private String isbn;
    @Column(nullable = false)
```

2024-01-28 15:14 UTC, merged