HW search books
savchenkoarts/online-book-store pull request #4
Opened 2024-12-18 14:24 UTC by savchenkoarts

2024-12-18 14:59 UTC, Elena-Bruyako requested changes
see comments

2024-12-18 14:59 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/dto/BookSearchParametersDto.java
> +        String title,
it's better to use array for parameters

2024-12-18 14:59 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/service/BookServiceImpl.java
> +        Specification<Book> byTitle =
what if you have 10 search parameters? 
Let's create SpecificationBuilder and SpecificationProvider for each parameter
or you can you BookSpecificationProvider with methods that return particular specificaiton

2024-12-22 11:01 UTC, okuzan approved these changes

2024-12-22 11:01 UTC, okuzan commented on src/main/java/mate/academy/onlinebookstore/specification/SpecificationProvider.java
> +    public Specification<Book> getSpecification(List<String> params, String fieldName) {
```suggestion
    public Specification<Book> getSpecification(List<String> params, String fieldName) {
        if (params == null || params.isEmpty()) {
             return null;
    }

```

2024-12-24 10:40 UTC, merged