Add CustomGlobalExceptionHandler class
savchenkoarts/online-book-store pull request #5
Opened 2024-12-30 11:52 UTC by savchenkoarts

Add CustomGlobalExceptionHandler class
Add meaningful validation for existing DTO classes

2024-12-30 12:32 UTC, Elena-Bruyako requested changes
see comments

2024-12-30 12:32 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/dto/CreateBookRequestDto.java
> +        @NotNull
for String 

```suggestion
        @NotBlank
```

2024-12-30 12:32 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/dto/UpdateBookRequestDto.java
> +        @NotNull
same here

2024-12-30 12:32 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, headers, status);
```suggestion
        return new ResponseEntity<>(body, headers, HttpStatus.BAD_REQUEST);
```

2024-12-30 12:32 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +    @NotNull
you can use or `@NotNull` or `@Column(nullable = false)`, read about which one is better

2024-12-30 12:32 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/03-add-not-null-constraint-to-title.yaml
> +        - addNotNullConstraint:
let's add `constraints: nullable: false` for `title` to existing changelog 01-create-book-table.yaml

2024-12-30 12:32 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/db.changelog-master.yaml
>        file: db/changelog/changes/02-add-isDeleted-column.yaml
same here,  add `is_deleted` column to existing changelog `01-create-book-table.yaml`

2024-12-30 23:11 UTC, savchenkoarts commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +    @NotNull
У статті [Hibernate @NotNull vs @Column(nullable = false)](https://www.baeldung.com/hibernate-notnull-vs-nullable) розглядаються відмінності між аннотаціями @NotNull та @Column(nullable = false) у JPA та Hibernate.
Ключові моменти:

-  @NotNull:
- Аннотація з пакету Bean Validation (JSR 303).
- Забезпечує валідацію на рівні Java, гарантуючи, що значення поля не є null перед збереженням у базу даних.
- Не впливає безпосередньо на структуру бази даних.
- @Column(nullable = false):
- Аннотація з JPA, яка визначає, що відповідна колонка в базі даних не може містити значення null.
- Використовується під час генерації схеми бази даних, додаючи обмеження NOT NULL до колонки.
- Не забезпечує валідацію на рівні Java; перевірка відбувається лише на рівні бази даних.

Рекомендації:

- Для повноцінної валідації рекомендується використовувати обидві аннотації одночасно.
- Це забезпечить перевірку на рівні Java (@NotNull) та на рівні бази даних (@Column(nullable = false)), підвищуючи загальну надійність застосунку.

Використання обох аннотацій гарантує, що помилки, пов’язані з null значеннями, будуть виявлені на ранніх етапах, що спрощує налагодження та підвищує стабільність системи.

Того вирішив залишити два варіанта, один для валідації на рівні бази даних, інший на рівні Java.

2024-12-30 23:17 UTC, savchenkoarts commented on src/main/resources/db/changelog/db.changelog-master.yaml
>        file: db/changelog/changes/02-add-isDeleted-column.yaml
З одного боку це порушує життевий цикил Liquibase і його призначення. У продакшен-середовищі буде грубою помилкою, як для портфоліо ОК.

2024-12-31 09:12 UTC, liliia-ponomarenko approved these changes
Good job! A few recomendations ;)

2024-12-31 09:12 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +public class CustomGlobalExceptionHandler extends ResponseEntityExceptionHandler {
you can also handle EntityNotFoundException

2024-12-31 09:12 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +    @NotBlank
you already validate dto on java level, so this annotation is redundant, but you can leave it if you want

2024-12-31 16:54 UTC, merged